### ISSUE TITLE
메인 페이지 디자인

### ISSUE THREAD

**Issue by pelly-ryu** [team-blackhole/UNIST-group-list-frontend#2]

**Comment by pelly-ryu** [comment]
현재 메인 페이지에 202동이라는 건물이 있는데 특별한 이유가 있나여
특정 건물에 대한 애착 같은 건가여
@mango-tree

**Comment by mango-tree** [comment]
그거 걍 의미 1도 없는 사진이에여
구역 잡아놓을라고 암거나 넣음

**Comment by pelly-ryu** [comment]
아하 난 또 첫사랑한테 단풍이 흐드러지는 가을날 202동 앞에서 차이신 줄

**Comment by mango-tree** [comment]
202동 앞이 아니란것만 빼면 맞군요..

**Comment by pelly-ryu** [comment]
ㅠㅠㅠㅠㅠㅠㅠ 왜 그러셈 ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

너무 슬프자너

**Comment by mango-tree** [comment]
흑흑흑
